### ISSUE TITLE
Losing Alpha channel

### ISSUE THREAD

**Issue by nachokb** [refile/refile-mini_magick#11]
I used refile 0.5.4 for a while, and just upgraded to 0.6.1 + refile_mini_magick.

I noticed that, previously, I was able to upload a PNG with transparency, and its resized thumbnails kept the alpha channel. Now it's lost, I get a white background. I fail to see where in the code this is done, as both `Refile::ImageProcessing` and `Refile::MiniMagick` look similar in these respect.

**Comment by jnicklas** [comment]
Are you sure you're not converting to another format?

**Comment by richardvenneman** [comment]
I can confirm that uploaded transparent PNG's lose their transparency to a white background on Refile 0.6.1

**Comment by janko** [comment]
Is the MiniMagick version the same? Maybe while updating Refile you also updated MiniMagick (Bundler would do that automatically for you).

**Comment by richardvenneman** [comment]
That could surely be the case.

Gemfile.lock:

```
mini_magick (4.3.3)
refile (0.6.1)
      mime-types
      rest-client (~> 1.8)
      sinatra (~> 1.4.5)
    refile-fog (0.2.0)
      fog
      refile
    refile-mini_magick (0.2.0)
      mini_magick (~> 4.0)
      refile (~> 0.5)
```

Please note that I don't have any experience with previous versions of Refile.

**Comment by janko** [comment]
Could you try to compose a MiniMagick code snippet that reproduces the problem? Just copy paste the code from refile-mini_magick and fill in with specific images. Then we'll know what's the actual and expected outcome and see is the problem in Refile or MiniMagick. Which processing method does this happen on?

**Comment by richardvenneman** [comment]
I think I tracked down the problem while setting up a testcase.

The background stays transparent after resizing with [this image](http://imgur.com/AJOoGyq), `mini_magick 4.3.3` and the following snippet:

``` ruby
require 'mini_magick'

image = MiniMagick::Image.open('in.png')
image.resize '50x50'
image.gravity 'Center'
image.write 'out.png'
```

However, when adding the [ImageMagick extent command](http://www.imagemagick.org/script/command-line-options.php#extent) (as in https://github.com/refile/refile-mini_magick/blob/master/lib/refile/mini_magick.rb#L81), the background of the output image will be white:

``` ruby
image.extent '50x50'
```

I'm not too comfortable with ImageMagick so I don't now if this is actually the fix and doesn't break any other stuff in the gem. Let me know if I can help in any other way.

**Comment by endorfin** [comment]
I have created a pull request https://github.com/refile/refile-mini_magick/pull/15 which solves the problem.

**Comment by janko** [comment]
#15 has been merged, see https://github.com/refile/refile-mini_magick/pull/15#issuecomment-256000597.
