### ISSUE TITLE
Moving forward to v1.0

### ISSUE THREAD

**Issue by nest4less-dev** [refile/refile-mini_magick#16]
Based on your recommendations, what needs to get done to move the version to 1.0? There are a number of PRs.

**Comment by thomasfedb** [comment]
Would be very keen to see a new release of this gem.

**Comment by leifcr** [comment]
@jnicklas I've used the current master in production for about 5 months (Since the merges in october), without any noticeable side-effects. Can you please do a 0.3 release on the current master branch?

**Comment by sobrinho** [comment]
Use master until we release a new version of refile and its libraries.

We are closing a lot of issues in Refile first.

**Comment by leifcr** [comment]
@sobrinho thanks
