### ISSUE TITLE
cant install gem if adding 'gem 'refile-mini_magick''

### ISSUE THREAD

**Issue by eddiefisher** [refile/refile-mini_magick#2]
https://github.com/refile/refile/issues/225

I'm added this line and get next error:
[Refile] image processing has been extracted into a separate gem, see https://github.com/refile/refile-mini_magick
than I'm added in Gemfile gem 'refile-mini_magick' but got new error
Could not find gem 'refile-mini_magick (>= 0) ruby' in the gems available on this machine.
than I'm change on gem 'refile-mini_magick', github: 'refile/refile-mini_magick'
and gem was installed, but I'm got error again
[Refile] image processing has been extracted into a separate gem, see https://github.com/refile/refile-mini_magick

ruby 2.2.0p0

gemfile:

```
gem 'rails', github: 'rails/rails', branch: '3-2-stable'
...
gem 'mini_magick'
gem 'refile', require: ['refile/rails', 'refile/image_processing'], github: 'refile/refile'
gem 'refile-mini_magick', github: 'refile/refile-mini_magick'
...
```

**Comment by jnicklas** [comment]
You should _not_ require refile/image_processing.

**Comment by eddiefisher** [comment]
I fined my error:
was:

```
class CustomImageProcessor < Refile::ImageProcessor
...
end
```

now:

```
class CustomImageProcessor < Refile::MiniMagick
...
end
```
