### ISSUE TITLE
Rack dependency needs to be updated to >= 2.0

### ISSUE THREAD

**Issue by dankozlowski** [refile/refile-mini_magick#21]
Rails 5.2.0 and greater depend on Rack >= 2.0, and this gem is locked to 1.5 or something.  Please update Rack!

**Comment by pedro-stanaka** [comment]
@dankozlowski  I managed to get it working by using the git repo directly instead of using a tagged version.
Like this:

```
gem "refile", require: "refile/rails", git: 'https://github.com/refile/refile'
gem "refile-mini_magick"
```

But refile should upload a new tag to rubygems this would update sinatra and rack version by collateral effect.

**Comment by sobrinho** [comment]
Thanks!

The problem is with the released version of refile, we are going to release a new version soon.
