### ISSUE TITLE
gem 'refile-mini_magick' is not found

### ISSUE THREAD

**Issue by kirillsalykin** [refile/refile-mini_magick#4]
ERROR:  Could not find a valid gem 'refile-mini_magick' (>= 0) in any repository

**Comment by jnicklas** [comment]
You're going to have to run this off the master branch for now.

**Comment by fabiode** [comment]
Nice! Using as the master branch.
Thanks!

Just saying, I've searched on ruby gems, but is not over there...
https://rubygems.org/search?utf8=%E2%9C%93&query=refile

**Comment by kohl00** [comment]
@jnicklas I'm getting this error also. What do you mean run this off the master branch? I ran bundle install from the master branch and got this error message
Could not find gem 'refile-mini_magick (>= 0) ruby' in the gems available on this machine.

gem file includes

gem 'mini_magick', '~> 4.2.4'
gem "refile", require: "refile/rails"
gem "refile-mini_magick"

**Comment by jnicklas** [comment]
Alright, I've released the gem. I was planning on waiting until the next version of Refile can be released, but I guess we can just bump the version then.
