### ISSUE TITLE
Limiting mini_magick memory usage

### ISSUE THREAD

**Issue by Sudrien** [refile/refile-mini_magick#5]
On my current VPS setup, an **identify -list resource** command shows ImageMagick thinking it has more memory to work with than is actually allocated to my VPS. As a result, I can pretty easily DOS myself with a single page, given sufficiently large files to thumbnail.

As it's a VPS, I should be able to change ImageMagick's policy.xml to use reasonable values, but per-application or per attribute options would be nice.

Via command line: http://www.imagemagick.org/script/command-line-options.php#limit

in mini_magick this can be achieved with calls like 

> cmd.limit "memory", "400MiB"
> cmd.limit "map", "400MiB"
> cmd.limit "disk", "1MiB"

Am I just missing where the proper place to put these options is?

**Comment by jnicklas** [comment]
Not sure if there's a global config option in MiniMagick to set this kind of stuff. There isn't anything in Refile at least.

**Comment by janko** [comment]
If your VPS has certain memory/disk limits, it seems reasonable for me to set it per-VPS, that is, in the policy.xml file. Is there a reason why you would want to set it per-application/attribute?

I think there is no pretty way to add it to Refile. I was thinking we could write the processing methods like this:

``` rb
def fit(img, width, height)
  img.combine_options do |cmd|
    # ...
    yield cmd if block_given?
    # ...
  end
end
```

And then you could override that method with

``` rb
Refile::MiniMagick.prepend Module.new {
  def fit(img, width, height) do
    super do |cmd|
      cmd.limit "memory", "400MiB"
      cmd.limit "map", "400MiB"
      cmd.limit "disk", "1MiB"
    end
  end
}
```

**Comment by Sudrien** [comment]
Part of the problem is, as far as I can tell, policy.xml isn't multi-instance aware. If I have 8 files being thumbnailed (which I very well could, from a single page render, depending on browser setup) the memory preferences would be much lower per file than they would be if I could force them to process serially.

**Comment by janko** [comment]
In #1 there was a similar request to make `Refile::MiniMagick` extendable using a dedicated API, but in https://github.com/refile/refile-mini_magick/issues/1#issuecomment-118537061 I explained why I don't think it would be a good idea. However, I will probably add an (undocumented) yield I proposed above, hopefully it should be good enough for both cases.
