### ISSUE TITLE
Video?

### ISSUE THREAD

**Issue by walterdavis** [refile/refile-mini_magick#6]
This is a bit of a rubber duck question, but I am hoping that larger brains than mine may have thought about this and are willing to share.

Since Refile's modus is strongly skewed toward just-in-time formatting, I am not sure this is going to ever work, but what would it take to do video transcoding within this framework? 

I am trying to replace a production Paperclip system, because direct upload to S3 (and multiple file uploads to S3) seems so very hard to do there. At least for static images, this is a distinctly straightforward thing to do in Refile. But video transcoding takes seconds or minutes per file, depending on size, so saving this task for the instant of (first) request is a real non-starter. 

Looking at the code in this gem, it seems pretty clear to me that I could fork it and wrap FFMPEG to do the actual grunt work needed. Has anyone else considered/started this? Any other thoughts about the duration issue?

Thanks,

Walter

**Comment by jnicklas** [comment]
Yeah, I think just-in-time processing is not a good choice for Video. It's barely acceptable for images. I think you should be able to do this with Refile, you're just going to have to do a bit more grunt work yourself. After an upload, start a transcoding job, and save the result back into a different attachment column, or something.
