### ISSUE TITLE
Is there support for multiple processors?

### ISSUE THREAD

**Issue by ghost** [refile/refile-mini_magick#8]
I love how the minimagick lib works, but one other thing I would maybe like to do is process the image through ImageOptim for example... but it seems I would have to fork the minimagick lib to do that?

Also, is there a way to control the compression of an uploaded jpg for example?

**Comment by jnicklas** [comment]
You don't have to fork it, you can simply call the `Refile::MiniMagick` methods from your own processor.

**Comment by ohenrik** [comment]
@jnicklas could you give an example on how to do this? By that i mean how do i add a process by default when i call the helper like so: `<%= attachment_url(@cover, :thumbnail, :fill, 1920, 1080) %>`
